version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=example_db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/mongodb
