### Example

###
GET http://localhost:4500/permissions

###
POST http://localhost:4500/permissions
Content-Type: application/json

{"name": "test-node-2", "description": "second test description node"}

###
GET http://localhost:4500/permissions/63cfd86a042b3f31fbba186d

###
PUT http://localhost:4500/permissions/63cfd86a042b3f31fbba186d
Content-Type: application/json

{"name": "test-node-changed", "description": "test description node changed!"}

###
DELETE http://localhost:4500/permissions/ID

### User

###
GET http://localhost:4500/users

###
POST http://localhost:4500/users
Content-Type: application/json

{"name": "user test node", "email":  "test-node@test.com", "role": ["63cfd86a042b3f31fbba186d"]}

###
PUT http://localhost:4500/users/63cfd884042b3f31fbba186e
Content-Type: application/json

{"name": "user test node changed", "email":  "test-node-2@test.com", "role": ["63cfd86a042b3f31fbba186d"]}

###
GET http://localhost:4500/users/63cfd884042b3f31fbba186e

###
DELETE http://localhost:4500/users/63c6e9005ffa8d5a00bbe557
