### Sample Endpoint HTTP

###
GET http://localhost:4500/sample/1

###
POST http://localhost:4500/sample
Content-Type: application/json

{"data": "sample data node"}

###
PUT http://localhost:4500/sample/1
Content-Type: application/json

{"data": "sample data node"}

###
DELETE http://localhost:4500/sample/1
